packages:
  - apps/*
  - packages/*

engineStrict: true
nodeVersion: 24.14.0
runtimeOnFail: error

allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': set this to true or false
  esbuild: true
  msgpackr-extract: true
  prisma: true
  sharp: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@nestjs/bull-shared@11.0.5'
  - '@nestjs/bullmq@11.0.5'
