import type { PrismaClient } from '@prisma/client';

type Item = { code: string; name: string; group: string; unit: string; price: number };
type Combo = { code: string; name: string; price: number };
const item = (code: string, name: string, group: string, price: number, unit = 'phần'): Item => ({ code, name, group, unit, price });

// Owner menu images supplied 2026-09-01. Prices include VAT.
const ITEMS: Item[] = [
  item('BA_CHI_HEO_BAN_NUONG', 'Ba chỉ heo bản nướng', 'MON_NUONG', 169000), item('SUON_HEO_NUONG', 'Sườn heo nướng', 'MON_NUONG', 159000), item('LONG_HEO_NUONG_CAY', 'Lòng heo nướng cay', 'MON_NUONG', 129000), item('BE_SUA_HEO_NUONG', 'Bẹ sữa heo nướng', 'MON_NUONG', 129000),
  item('BO_BA_CHI_MY_NUONG', 'Bò ba chỉ Mỹ nướng', 'MON_NUONG', 139000), item('LUOI_BO_NUONG', 'Lưỡi bò nướng', 'MON_NUONG', 199000), item('LOI_VAI_BO_AUKOBE_NUONG', 'Lõi vai bò AUKOBE nướng', 'MON_NUONG', 209000), item('TOM_NUONG_MUOI', 'Tôm nướng muối', 'MON_NUONG', 109000), item('BACH_TUOC_NUONG_CAY', 'Bạch tuộc nướng cay', 'MON_NUONG', 199000),
  item('XIEN_THIT_HEO_NUONG_GIENG_ME', 'Xiên thịt heo nướng giềng mẻ', 'MON_NUONG', 169000), item('XIEN_BO_NUONG_CU_QUA', 'Xiên bò nướng củ quả', 'MON_NUONG', 219000), item('XIEN_GA_NUONG_CAY', 'Xiên gà nướng cay', 'MON_NUONG', 119000), item('GA_NUONG_NGUYEN_CON', 'Gà nướng nguyên con', 'MON_NUONG', 499000), item('GA_DEN_NUONG_NGUYEN_CON', 'Gà đen nướng nguyên con', 'MON_NUONG', 619000), item('CA_TAM_NUONG_GIENG_ME', 'Cá tầm nướng giềng mẻ', 'MON_NUONG', 299000),
  item('LAU_GA_DEN_VUON_MANG_DEN', 'Lẩu gà đen Vườn Măng Đen', 'MON_LAU', 429000), item('LAU_CA_TAM_MANG_RUNG', 'Lẩu cá tầm măng rừng Vườn Măng Đen', 'MON_LAU', 319000), item('LAU_ECH_MANG_CAY', 'Lẩu ếch măng cay', 'MON_LAU', 350000), item('CA_TAM_THEM', 'Cá tầm thêm', 'MON_LAU', 250000), item('MANG_ECH_THEM_NHO', 'Măng ếch thêm phần nhỏ', 'MON_LAU', 180000), item('MANG_ECH_THEM_LON', 'Măng ếch thêm phần lớn', 'MON_LAU', 250000), item('GA_DEN_THEM_NUA_CON', 'Gà đen thêm 1/2 con', 'MON_LAU', 219000), item('GA_DEN_THEM_MOT_CON', 'Gà đen thêm 1 con', 'MON_LAU', 429000), item('MOC_GION_THEM', 'Mọc giòn thêm', 'MON_LAU', 99000), item('BAP_BO_THEM', 'Bắp bò thêm', 'MON_LAU', 129000), item('RAU_NHUNG_LAU', 'Rau nhúng lẩu', 'MON_LAU', 30000), item('NAM_THEM', 'Nấm thêm', 'MON_LAU', 30000), item('VANG_DAU_THEM', 'Váng đậu thêm', 'MON_LAU', 30000), item('TAU_HU_THEM', 'Tàu hũ thêm', 'MON_LAU', 25000), item('NGO_NGOT_THEM', 'Ngô ngọt thêm', 'MON_LAU', 20000), item('NGAI_CUU_THEM', 'Ngải cứu thêm', 'MON_LAU', 30000), item('LA_SAM_DAY_THEM', 'Lá sâm dây thêm', 'MON_LAU', 45000), item('MI_TOM_THEM', 'Mì tôm thêm (2 gói)', 'MON_LAU', 15000),
  item('GOI_HOA_CHUOI_RUNG_BO_GAC_BEP', 'Gỏi hoa chuối rừng Măng Đen – bò gác bếp', 'GOI_SALAD_KHAI_VI', 155000), item('GOI_CAI_MAM', 'Gỏi cải mầm Vườn Măng Đen', 'GOI_SALAD_KHAI_VI', 95000), item('SOUP_CA_TAM', 'Soup cá tầm Măng Đen', 'GOI_SALAD_KHAI_VI', 50000), item('GOI_BO_CA_PHAO_BAP_BO', 'Gỏi bò cà pháo bắp bò', 'GOI_SALAD_KHAI_VI', 119000),
  item('TOP_MO_HEO_BAN', 'Tóp mỡ heo bản chiên giòn', 'RAU_MON_AN_NHE', 135000), item('DOI_SUN', 'Dồi sụn', 'RAU_MON_AN_NHE', 110000), item('NEM_CHUA_RAN', 'Nem chua rán', 'RAU_MON_AN_NHE', 60000), item('CHA_CA_TAM_THI_LA', 'Chả cá tầm thì là', 'RAU_MON_AN_NHE', 170000), item('CHA_COM_LANG_VONG', 'Chả cốm làng Vòng', 'RAU_MON_AN_NHE', 45000), item('NEM_CA_TAM', 'Nem cá tầm', 'RAU_MON_AN_NHE', 150000), item('CHA_MUC_HA_LONG', 'Chả mực Hạ Long', 'RAU_MON_AN_NHE', 145000),
  item('RAU_LUI_LUOC_MUOI_ME', 'Rau lủi rừng Măng Đen luộc muối mè', 'RAU_MON_AN_NHE', 55000), item('RAU_LUI_XAO_OT_TOI', 'Rau lủi rừng Măng Đen xào ớt tỏi', 'RAU_MON_AN_NHE', 59000), item('RAU_LUI_XAO_BO', 'Rau lủi rừng Măng Đen xào bò', 'RAU_MON_AN_NHE', 145000), item('MANG_RUNG_LUOC_MUOI_ME', 'Măng rừng tươi luộc chấm muối mè', 'RAU_MON_AN_NHE', 65000), item('MANG_RUNG_XAO_BO', 'Măng rừng tươi xào bò', 'RAU_MON_AN_NHE', 179000), item('KHOAI_LANG_CHIEN_ME_DEN', 'Khoai lang Măng Đen chiên mè đen', 'RAU_MON_AN_NHE', 70000), item('KHOAI_LANG_NUONG_PHOMAI', 'Khoai lang Măng Đen nướng phomai', 'RAU_MON_AN_NHE', 90000), item('QUA_SU_LUOC', 'Quả su luộc chấm muối mè', 'RAU_MON_AN_NHE', 50000), item('NGON_SU_SU_LUOC', 'Ngọn su su luộc', 'RAU_MON_AN_NHE', 55000), item('NGON_SU_SU_XAO_TOP_MO', 'Ngọn su su xào tóp mỡ', 'RAU_MON_AN_NHE', 80000), item('RAU_MUNG_TOI_XAO_TOI', 'Rau mùng tơi xào tỏi', 'RAU_MON_AN_NHE', 55000), item('NAM_NUONG', 'Nấm nướng Vườn Măng Đen', 'RAU_MON_AN_NHE', 89000), item('NGO_NGOT_NUONG', 'Ngô ngọt nướng', 'RAU_MON_AN_NHE', 20000), item('SET_RAU_CU_NUONG', 'Set rau củ nướng Măng Đen', 'RAU_MON_AN_NHE', 50000), item('COM_LAM_NUONG', 'Cơm lam nướng / chiên chấm muối vừng', 'RAU_MON_AN_NHE', 20000),
  item('SOT_ME_RANG', 'Sốt mè rang', 'SOT_CHAM', 0), item('SOT_NUI_RUNG', 'Sốt núi rừng Măng Đen', 'SOT_CHAM', 0), item('SOT_BBQ', 'Sốt BBQ', 'SOT_CHAM', 0), item('SOT_MUOI_DO', 'Sốt muối đỏ', 'SOT_CHAM', 0),
  item('BIA_TIGER_LON', 'Bia Tiger lon', 'DO_UONG', 25000, 'lon'), item('BIA_HEINEKEN_LON', 'Bia Heineken lon', 'DO_UONG', 28000, 'lon'), item('BIA_SAIGON_SPECIAL', 'Bia Saigon Special lon', 'DO_UONG', 25000, 'lon'), item('BIA_HA_NOI_LON', 'Bia Hà Nội lon', 'DO_UONG', 22000, 'lon'), item('BIA_333_LON', 'Bia 333 lon', 'DO_UONG', 22000, 'lon'), item('COCA_COLA_LON', 'Coca Cola lon', 'DO_UONG', 18000, 'lon'), item('COCA_COLA_ZERO_LON', 'Coca Cola Zero lon', 'DO_UONG', 18000, 'lon'), item('SPRITE_LON', 'Sprite lon', 'DO_UONG', 18000, 'lon'), item('FANTA_CAM_LON', 'Fanta cam lon', 'DO_UONG', 18000, 'lon'), item('NUOC_LOC', 'Nước lọc', 'DO_UONG', 10000, 'chai'), item('NUOC_MO_HA_NOI', 'Nước mơ Hà Nội', 'DO_UONG', 25000), item('NUOC_SAU_HA_NOI', 'Nước sấu Hà Nội', 'DO_UONG', 25000), item('RUOU_SOJU', 'Rượu Soju', 'DO_UONG', 99000, 'chai'),
];
const COMBOS: Combo[] = [
  { code: 'SET_NUONG_TU_KHOAI', name: 'Set nướng Tứ Khoái', price: 369000 }, { code: 'SET_NUONG_NGU_CUNG', name: 'Set nướng Ngũ Cung', price: 439000 }, { code: 'SET_VUON_MANG_DEN', name: 'Set Vườn Măng Đen lẩu + nướng', price: 799000 }, { code: 'SET_CA_TAM_MANG_DEN', name: 'Set cá tầm Măng Đen', price: 999000 },
];

export async function seedBbqMenu(prisma: PrismaClient): Promise<void> {
  for (const [displayOrder, entry] of ITEMS.entries()) await prisma.bbqMenuItem.upsert({ where: { code: entry.code }, update: { name: entry.name, menuGroup: entry.group, unit: entry.unit, price: BigInt(entry.price), publicDescription: null, internalNote: null, isAvailable: true, displayOrder }, create: { code: entry.code, name: entry.name, menuGroup: entry.group, unit: entry.unit, price: BigInt(entry.price), isAvailable: true, displayOrder } });
  for (const [displayOrder, entry] of COMBOS.entries()) await prisma.bbqCombo.upsert({ where: { code: entry.code }, update: { name: entry.name, price: BigInt(entry.price), minGuests: null, maxGuests: null, composition: null, internalNote: null, isAvailable: true, displayOrder }, create: { code: entry.code, name: entry.name, price: BigInt(entry.price), isAvailable: true, displayOrder } });
  await prisma.bbqMenuItem.updateMany({ where: { code: { notIn: ITEMS.map((entry) => entry.code) } }, data: { isAvailable: false } });
  await prisma.bbqCombo.updateMany({ where: { code: { notIn: COMBOS.map((entry) => entry.code) } }, data: { isAvailable: false } });
  console.log(`BBQ production menu seeded: ${ITEMS.length} items and ${COMBOS.length} sets; prices include VAT.`);
}
